conversions:
  markdown_pdf:
    - input: ./Rules/README.md
      output: ./../Assets/Rules/Stanton City Park Rules.pdf
    - input: ./Rules/LeagueRules/README.md
      output: ./../../Assets/Rules/LeagueRules/Stanton City Park League Rules.pdf
    - input: ./Rules/LeagueRules/Adult/Basketball/README.md
      output: ./../../../Assets/Rules/LeagueRules/Adult/Basketball/Stanton City Park League Adult Basketball Rules.pdf
    - input: ./Rules/LeagueRules/Adult/Softball/README.md
      output: ./../../../Assets/Rules/LeagueRules/Adult/Softball/Stanton City Park League Adult Softball Rules.pdf
    - input: ./Rules/LeagueRules/Youth/Baseball/README.md
      output: ./../../../Assets/Rules/LeagueRules/Youth/Baseball/Stanton City Park League Youth Baseball Rules.pdf
    - input: ./Rules/LeagueRules/Youth/Soccer/README.md
      output: ./../../../Assets/Rules/LeagueRules/Youth/Soccer/Stanton City Park League Soccer Rules.pdf
    - input: ./Rules/LeagueRules/Youth/Softball/README.md
      output: ./../../../Assets/Rules/LeagueRules/Youth/Softball/Stanton City Park League Softball Rules.pdf
    - input: ./Rules/AttractionRules/BattingCageRules/README.md
      output: ./../../../Assets/Rules/AttractionRules/BattingCageRules/Stanton City Park Batting Cage Rules.pdf
